server:
    port: ${PORT:8000}
    tomcat:
        threads:
            max: 1000
            min-spare: 10

spring:
    application:
        name: mockboard
    main:
        banner-mode: off
    profiles:
        active: ${ACTIVE_ENV:dev}
    threads:
        virtual:
            enabled: ${VI_THREADS:true}
    datasource:
        url: 'jdbc:h2:file:../data/mockboard_dev;MODE=MySQL;AUTO_SERVER=TRUE'
        driver-class-name: org.h2.Driver
        username: sa
        password:
        hikari:
            maximum-pool-size: 20
            minimum-idle: 5
            connection-timeout: 30000
    sql:
      init:
          mode: always
          schema-locations: classpath:db/schema.sql